name: Bug Report
description: Create a report about a bug / an error
title: "[Bug]: Help my pc got hacked!!"
labels: ["Bug"]
body:
  - type: dropdown
    id: bug-type
    attributes:
      label: What Type of Bug is it?
      options:
        - Unexpected Behavior
        - Crash
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      description: What version of Forge are you using? *latest* is NOT a version.
      placeholder: "40.1.0"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the Mod are you using? *latest* is NOT a version.
      placeholder: "1.2"
    validations:
      required: true
  - type: input
    id: game-log-crash
    attributes:
      label: Game Log / Crash
      description: A **[Github Gist](https://gist.github.com/)** link to the full `debug.log` file. You can find it in `.minecraft\logs\debug.log`. If the bug type is a *Crash* please also provide a link to the crash report. You can find it in `.minecraft\crash-reports\crash-<date>.txt`
      placeholder: "https://gist.github.com/YourName/abcdefghijklmnopqrstuvwxyx012345"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: A list of how you encountered this bug.
      placeholder: |
        1. Start Minecraft
        2. Generate a new world
        3. Summon Killerzombie
        4. '....'
        5. Minecraft and all other opened programs crash and my pc gets hacked
    validations:
      required: true
  - type: textarea
    attributes:
      label: What You Expect To Happen
      description: Describe what you thought was supposed to have happened. Don't worry if you think what you expected may be wrong.
      placeholder: "Minecraft shouldn't crash and my pc shouldn't get hacked"
    validations:
      required: true
  - type: textarea
    attributes:
      label: What Actually Happened
      description: Describe what happened to you that wasn't to expectations.
      placeholder: "Minecraft crashed and my pc got hacked!!1!1"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other Details / Screenshots
      description: If applicable, add other details and/or screenshots to help explain your problem.
      placeholder: "I didn't install a Virus before using the mod"
    validations:
      required: false
  - type: checkboxes
    id: confirmation
    attributes:
      label: Please Confirm The following Checkboxes
      options:
        - label: I have confirmed this bug can be replicated without using *Optifine*.
          required: true
        - label: I have confirmed this bug is on the most recently supported version.
          required: true
        - label: I have confirmed this issue has not been reported already.
          required: true
